package cat.paucasesnovescifp.simulapinstructor;

import cat.paucasesnovescifp.simulapinstructor.dataaccess.DataAccess;
import cat.paucasesnovescifp.simulapinstructor.models.Usuari;
import cat.paucasesnovescifp.simulapinstructor.views.LoginPanel;
import cat.paucasesnovescifp.simulapinstructor.views.UserInfoPanel;

/**
 *
 * @author Miguel
 */
public class Main extends javax.swing.JFrame {

    private Usuari usuari = null;
    private LoginPanel pnlLogin = null;
    private UserInfoPanel pnlUserInfo = null;
    private DataAccess dataAccess = null;
    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        setTitle("Simulap instructor U+1F4AA");
        setSize(1024, 768);
        dataAccess = new DataAccess();
        
        if (usuari == null) {
            pnlLogin = new LoginPanel(this);
            pnlLoginContainer.add(pnlLogin);
        }
        else {
            pnlLoginContainer.removeAll();
        }
    }

    public void userLoggedIn(Usuari user) {
        this.usuari = user;
        pnlLoginContainer.removeAll();
        pnlLogin = null;
        pnlUserInfo = new UserInfoPanel(this, usuari);
        pnlLoginContainer.add(pnlUserInfo);
        repaint();
    }
    
    public void userLoggedOut() {
        this.usuari = null;
        pnlLoginContainer.removeAll();
        pnlUserInfo = null;
        pnlLogin = new LoginPanel(this);
        pnlLoginContainer.add(pnlLogin);
        repaint();
        //clear all other panels
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        pnlLoginContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlLeft.setLayout(null);

        pnlLoginContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        pnlLoginContainer.setOpaque(false);
        pnlLoginContainer.setLayout(null);
        pnlLeft.add(pnlLoginContainer);
        pnlLoginContainer.setBounds(0, 10, 300, 300);
        pnlLoginContainer.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlLeft);
        pnlLeft.setBounds(0, 0, 300, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlLoginContainer;
    // End of variables declaration//GEN-END:variables

    public Usuari getUsuari() {
        return usuari;
    }

    public void setUsuari(Usuari usuari) {
        this.usuari = usuari;
    }
}
