/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.paucasesnovescifp.simulapinstructor.views;

import cat.paucasesnovescifp.simulapinstructor.Main;
import cat.paucasesnovescifp.simulapinstructor.dataaccess.DataAccess;
import cat.paucasesnovescifp.simulapinstructor.models.Usuari;
import javax.swing.JOptionPane;
import at.favre.lib.crypto.bcrypt.BCrypt;
import java.util.Base64;

/**
 *
 * @author Miguel
 */
public class LoginPanel extends javax.swing.JPanel {

    private Main _main = null;

    /**
     * Creates new form pnlLogin
     */
    public LoginPanel(Main mainFrame) {
        _main = mainFrame;
        initComponents();
        this.setBounds(20, 20, 260, 260);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 1, true));
        setMinimumSize(new java.awt.Dimension(260, 200));
        setPreferredSize(new java.awt.Dimension(260, 200));
        setLayout(null);

        txtEmail.setText("a@b.c");
        add(txtEmail);
        txtEmail.setBounds(10, 23, 200, 22);

        txtPassword.setText("string");
        add(txtPassword);
        txtPassword.setBounds(10, 60, 200, 22);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(140, 100, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        DataAccess dataAccess = new DataAccess();
        Usuari usuari = dataAccess.getUser(txtEmail.getText());
        if (usuari.getId() == 0) {
            // Error
            JOptionPane.showMessageDialog(_main, txtEmail.getText() + " no existe", "Login error", JOptionPane.ERROR_MESSAGE);
        } else {
            /* This works */
            char[] passwordToVerify = txtPassword.getPassword();
            String userPasswordHashInDatabase = usuari.getPasswordHash();
//            byte[] userPasswordHash = usuari.getPasswordHash();

            var result = BCrypt.verifyer().verify(passwordToVerify, userPasswordHashInDatabase);

            if (result.verified) {
                if (usuari.isInstructor()) {
                    _main.userLoggedIn(usuari);
                } else {
                    JOptionPane.showMessageDialog(_main, "You must be an instructor to log in!", "Login error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(_main, "Wrong password for " + txtEmail.getText(), "Login error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
