package cat.paucasesnovescifp.simulapinstructor.views;

import cat.paucasesnovescifp.simulapinstructor.Main;
import cat.paucasesnovescifp.simulapinstructor.models.Usuari;

/**
 *
 * @author Miguel
 */
public class UserInfoPanel extends javax.swing.JPanel {
    private Usuari _user = null;
    private Main _main = null;
    /**
     * Creates new form UserInfoPanel
     */
    public UserInfoPanel(Main main, Usuari user) {
        initComponents();
        _main = main;
        _user = user;
        this.setBounds(20, 20, 260, 260);
        lblUsername.setText(_user.getNom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblMessages = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 1, true));
        setMinimumSize(new java.awt.Dimension(260, 260));
        setPreferredSize(new java.awt.Dimension(260, 260));
        setLayout(null);

        lblUsername.setText("Javier Garia Instructor");
        add(lblUsername);
        lblUsername.setBounds(20, 20, 200, 16);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout);
        btnLogout.setBounds(150, 200, 72, 23);

        lblMessages.setText("Tiene x ejercicios pendientes de revisar");
        add(lblMessages);
        lblMessages.setBounds(20, 50, 210, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        _main.userLoggedOut();
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel lblMessages;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
